import { Noto_Sans_Khmer } from "next/font/google";
import "./globals.css";
import Layout from "./components/Layout";
import { ThemeProvider } from "next-themes";

const inter = Noto_Sans_Khmer({ subsets: ["khmer"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
